chore: Update Go to 1.26.0 and golangci-lint to v2.10.0
Co-authored-by: Leo Antoli <lantoli@users.noreply.github.com>

---
Squashed commits (oldest first):
- b07fe0e: chore: Update Go to 1.26.0 and golangci-lint to v2.10.0
- e5b1273: fix: Rename package from 'flag' to 'flags' to avoid standard library conflict
- 808b116: refactor: Rename package directory from flag to flags
- f604b0d: updated-files-check
- b79f0ec: go fix command
- 2519bb4: adjust error comment
- 81705bb: Revert "go fix command"
- 4aae3f3: Reapply "go fix command"
- dab8489: rename Go file

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -48,7 +48,7 @@ jobs:
       - name: golangci-lint
         uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
         with:
-          version: v2.8.0 # Also update GOLANGCI_VERSION variable in Makefile when updating this version
+          version: v2.10.0 # Also update GOLANGCI_VERSION variable in Makefile when updating this version
       - name: actionlint
         run: |
           make tools
@@ -57,3 +57,25 @@ jobs:
         shell: bash
       - name: shellcheck
         uses: bewuethr/shellcheck-action@80bac2daa9fcf95d648200a793d00060857e6dc4
+
+  check-go-files:
+      runs-on: ubuntu-latest
+      permissions: {}
+      steps:
+        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+        - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5    
+          with:
+            go-version-file: 'go.mod'  
+        - run: go mod tidy
+        - run: go fix ./...
+        - name: Find mutations
+          id: self_mutation
+          run: |-
+            git add .
+            git diff --staged --patch --exit-code > doc.repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
+        - name: Fail build on mutation
+          if: steps.self_mutation.outputs.self_mutation_happened
+          run: |-
+            echo "::error::Files were changed. Make sure to run 'go mod tidy' and 'go fix ./...'"
+            cat doc.repo.patch
+            exit 1
